### ISSUE TITLE
How to use with folders?

### ISSUE THREAD

**Issue by rkkmistry** [Obbut/iCloud-Control#1]
First of all--thanks for putting this together.

Right now, I can only remove/download if I've selected the particular file(s). Is it possible to remove/download entire folders? Or is there some way to run these actions from the command line so I can programmatically select everything in a folder?

**Comment by Obbut** [comment]
For me, it does work fine with folders. However, the folder itself won't be evicted, only the files residing inside of it. Finder also won't show the cloud icon indicating that an item is available for download for folders, only for files.

**Comment by rkkmistry** [comment]
Ok - it appears to be working now that I'm not trying from the most top level folder - thanks!

**Comment by Obbut** [comment]
The issue is fixed with version 1.1, it should work fine with folders now, also in column view.
