### ISSUE TITLE
ToolBar Icon not showing on 10.14.2

### ISSUE THREAD

**Issue by hstriepe** [Obbut/iCloud-Control#13]
My system was upgraded tp Mojave running iCloud Control 1.1 a while back. All was working ok.

I upgraded to the newer rev and it is neither showing on the Toolbar nor in customization.
- Extension has been added
- I have added to to full disk access just in case

Any thoughts?

**Comment by thinkJD** [comment]
Have you tried to restart (Force Quit) Finder? 

`sudo killall Finder`

**Comment by hstriepe** [comment]
Yup. Even I also end up with Finder crashes until disabling and logging out.

**Comment by hstriepe** [comment]
Now working ok. Go figure!
