### ISSUE TITLE
Publish Public Link is not working on Mac OS 10.12.3

### ISSUE THREAD

**Issue by pasl** [Obbut/iCloud-Control#2]
Hi

I tried iCloud-Control with Mac OS 10.12.3.  It seems to work fine except for "Publish Public Link".

When I choose "Publish Public Link" the clipboard empty itself and I don't get anything.

Thank you

Pascal

**Comment by Obbut** [comment]
The publish link feature only works on files, are you targeting a file or a folder?

**Comment by Obbut** [comment]
I noticed it it broken for me too right now, but it was working a few days ago when I last used it. I will investigate but I'm really busy at the moment so it can take a while.

Thanks for reporting!

**Comment by pasl** [comment]
Yes I confirm it's on file. 

Thank you it's a great addition to iCloud.

**Comment by Obbut** [comment]
It seems to work again, so I'm closing this issue. Feel free to open another one if you have any issues.
