### ISSUE TITLE
V1.2 not working on Sierra 1.12.6, V1.1 works

### ISSUE THREAD

**Issue by hstriepe** [Obbut/iCloud-Control#20]
Title says it all. I have tried all permutations including removing all other Finder extensions. killing the Finder, etc.

I can switch back and forth. V1.1 shows up on the Toolbar, v1.2 does not. V1.2 works for me on Mojave.

**Comment by mrfrasier** [comment]
Sorry you haven't found a solution, but thank you for making the post. I couldn't get it to work either, but dropping down to 1.1 as you mentioned, did the trick.

**Comment by hstriepe** [comment]
Thanks.
