### ISSUE TITLE
Why Remove selected item locally is not working?

### ISSUE THREAD

**Issue by yGuxian** [Obbut/iCloud-Control#3]
Hello

It's finally found your software that I have been looking for, but "Remove selected item locally" is not working. My environment is mac OS sierra 10.12.3. I selected a folder or file on the finder, and selected a "Remove selected item locally" in menu, but any items is not removed.

Thank you

Tomohiro

**Comment by Obbut** [comment]
Hi, are you sure the problem isn't the same as [this one](https://github.com/Obbut/iCloud-Control/issues/1)? Does it work on single files (not folders)?

**Comment by yGuxian** [comment]
Hello, I have tried it in one file or one folder, but it couldn't remove any files/folders. I don't know whether my environment is relating whith this cause.  Is there I should do for solve it?

**Comment by Obbut** [comment]
Hi Tomohiro, do you still have this issue or is it solved for you?
