### ISSUE TITLE
Non-synced items are forgotten after a reboot

### ISSUE THREAD

**Issue by m4rkw** [Obbut/iCloud-Control#4]
It seems that if items are deleted locally (and thus marked as not-to-sync), this is forgotten after a reboot.

Is there a way to set the no-sync status via the commandline so I can automate the process of persisting these settings after a reboot?

**Comment by Obbut** [comment]
I'm not aware of an existing way to set the sync status via the command line, but you could use the code from this repo to build a utility to do this yourself.

As for the status not persisting: Do you have iCloud drive set to "Optimize Mac storage" in System Preferences? If not, maybe iCloud will always download everything.
